# Generated by Django 2.1 on 2018-08-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20180830_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampasscode',
            name='passcode',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
