# Generated by Django 2.1 on 2018-09-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20180830_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
