# Generated by Django 2.1 on 2018-09-04 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_1_score', models.IntegerField(blank=True, null=True)),
                ('team_2_score', models.IntegerField(blank=True, null=True)),
                ('round', models.IntegerField(blank=True, null=True)),
                ('team_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='teams.Team')),
                ('team_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='teams.Team')),
                ('winner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_winner', to='teams.Team')),
            ],
        ),
    ]
