# Generated by Django 2.1 on 2018-09-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0006_match_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='round',
        ),
    ]
