# Generated by Django 2.1 on 2018-09-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0012_auto_20180905_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team_1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
