# Generated by Django 2.1 on 2018-09-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('bracket', '0013_auto_20180905_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BYE', 'BYE'), ('Not Scheduled', 'Not Scheduled'), ('Scheduled', 'Scheduled'), ('Finished', 'Finished')], default='Not Scheduled', max_length=20)),
                ('team_1_score', models.PositiveIntegerField(blank=True, null=True)),
                ('team_2_score', models.PositiveIntegerField(blank=True, null=True)),
                ('match_round', models.IntegerField()),
                ('team_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='teams.Team')),
                ('team_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='teams.Team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('current_round', models.IntegerField(default=0)),
                ('rounds', models.IntegerField(default=0)),
                ('icon', models.ImageField(blank=True, upload_to='static/icons', verbose_name='image')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='bracket.Tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_winner', to='teams.Team'),
        ),
    ]
