# Generated by Django 2.1 on 2018-09-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0014_auto_20180905_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_round',
            field=models.IntegerField(default=1),
        ),
    ]
