# Generated by Django 2.1 on 2018-09-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0015_auto_20180905_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_number',
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
