# Generated by Django 2.1 on 2018-09-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0016_auto_20180905_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_1_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
