# Generated by Django 2.1 on 2018-09-06 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0017_auto_20180905_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='teams.Team'),
        ),
    ]
