# Generated by Django 2.1 on 2018-09-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0018_auto_20180906_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='seed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
